image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  IMPALA_HOST: impala
  IMPALA_PORT: "21000"
  COMPlus_DebugWriteToStdErr: "1"

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build
  except:
    changes:
      - "*.md"

test:
  stage: test
  services:
    - name: codingtony/impala
      alias: impala

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/ImpalaSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init ImpalaSupplyCollector impala://$IMPALA_HOST:$IMPALA_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit ImpalaSupplyCollector impala://$IMPALA_HOST:$IMPALA_PORT
    - cd $ROOT_PROJECT_PATH
    - dotnet test

  except:
    changes:
      - "*.md"

load_test:
  stage: test
  services:
    - name: codingtony/impala
      alias: impala

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/ImpalaSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init ImpalaSupplyCollector impala://$IMPALA_HOST:$IMPALA_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit ImpalaSupplyCollector impala://$IMPALA_HOST:$IMPALA_PORT
    - dotnet SupplyCollectorDataLoader.dll -samples ImpalaSupplyCollector impala://$IMPALA_HOST:$IMPALA_PORT TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/ImpalaSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness

  except:
    changes:
      - "*.md"
